{% set name = "wslPath" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wslPath-{{ version }}.zip
  sha256: da0dc8efebec4966565366854b6530de5585d3a7c871cb0b039a2a1ac9bb9155

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - wslPath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akikuno/wslPath
  summary: Python module to convert between Windows and POSIX path in WSL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akikuno
